[CmdletBinding()]
param(
    [string]$ResultsRoot = '.\results',
    [string]$PublishRoot = '.\results\publish',
    [string]$Title = 'RetroDojo Device Bench Suite -- Comparison Results'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-SuitePath {
    param([Parameter(Mandatory = $true)][string]$Path)

    if ([System.IO.Path]::IsPathRooted($Path)) {
        return [System.IO.Path]::GetFullPath($Path)
    }

    return [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot $Path))
}

function Write-Utf8NoBomFile {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [AllowEmptyString()][string]$Content
    )

    [System.IO.File]::WriteAllText($Path, $Content, [System.Text.UTF8Encoding]::new($false))
}

$resolvedResultsRoot = Resolve-SuitePath -Path $ResultsRoot
$chartsDir = Join-Path $resolvedResultsRoot 'comparison-charts'
$chartsHtmlPath = Join-Path $chartsDir 'comparison-charts.html'
$chartsDataPath = Join-Path $chartsDir 'comparison-charts-data.json'

if (-not (Test-Path -LiteralPath $chartsHtmlPath) -or -not (Test-Path -LiteralPath $chartsDataPath)) {
    throw "Comparison charts not found under '$chartsDir'. Run New-ComparisonDataset.ps1 then New-ComparisonCharts.ps1 first."
}

$resolvedPublishRoot = Resolve-SuitePath -Path $PublishRoot
if (-not (Test-Path -LiteralPath $resolvedPublishRoot)) {
    New-Item -ItemType Directory -Path $resolvedPublishRoot -Force | Out-Null
}

# NOTE: comparison-charts-data.json is already public-safe (device is a friendly label like
# "RPC6"/"RG476H", no adb_serial/build_fingerprint/product_model fields) -- confirmed by inspecting
# New-ComparisonCharts.ps1's chart-data schema (bar_data: device/value/rows, thermal_series:
# device/run_id/app/thermal_zone/thermal_zone_avg_c/points). Nothing further to redact here, but this
# script is the single choke point for anything published externally, so add redaction here if the
# chart-data schema ever grows to include raw run metadata.
Copy-Item -LiteralPath $chartsHtmlPath -Destination (Join-Path $resolvedPublishRoot 'comparison-charts.html') -Force
Copy-Item -LiteralPath $chartsDataPath -Destination (Join-Path $resolvedPublishRoot 'comparison-charts-data.json') -Force

$dataJson = Get-Content -LiteralPath $chartsDataPath -Raw | ConvertFrom-Json
$generatedAt = $dataJson.generated_at
if (-not $generatedAt) {
    $generatedAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
}

$titleEscaped = [System.Net.WebUtility]::HtmlEncode($Title)
$indexHtml = @"
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>$titleEscaped</title>
<style>
  body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; background:#0d0d10; color:#eee; margin:0; padding:2rem; }
  a.button { display:inline-block; padding:0.75rem 1.25rem; background:#3d7bfd; color:#fff; text-decoration:none; border-radius:6px; font-weight:600; }
  a.button:hover { background:#5a90ff; }
  .meta { color:#9aa0a6; margin-top:0.5rem; }
  .card { background:#17171c; border:1px solid #2a2a31; border-radius:10px; padding:1.5rem; max-width:640px; margin-top:1.5rem; }
</style>
</head>
<body>
<h1>$titleEscaped</h1>
<div class="meta">Generated: $generatedAt</div>
<div class="card">
  <p>Cross-device benchmark comparison charts (CPU/GPU utilization, thermal timelines) generated by the
  RetroDojo RD Gauntlet. Static export -- safe to share; contains no serial numbers, build
  fingerprints, or other per-device identifying metadata.</p>
  <p><a class="button" href="comparison-charts.html">View comparison charts &rarr;</a></p>
</div>
</body>
</html>
"@

Write-Utf8NoBomFile -Path (Join-Path $resolvedPublishRoot 'index.html') -Content $indexHtml

Write-Host "Published static results to: $resolvedPublishRoot"
Write-Host "  - index.html"
Write-Host "  - comparison-charts.html"
Write-Host "  - comparison-charts-data.json"
